version: '3.9'

services:
  bot:
    build:
      context: ./bot
    container_name: fast_food_bot
    restart: always
    env_file:
      - ./bot/.env
    volumes:
      - ./media:/app/media
    depends_on:
      - db
    networks:
      - fast_food-network

  management:
    build:
      context: ./management
    container_name: fast_food_admin
    restart: always
    env_file:
      - ./management/.env
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - fast_food-network

  db:
    image: postgres:15
    container_name: fast_food_db
    restart: always
    env_file:
      - ./db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - fast_food-network

volumes:
  postgres_data:

networks:
  fast_food-network:
    driver: bridge
